create table if not exists public.crunch_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null check (status in ('active', 'submitted', 'verified', 'rejected', 'abandoned')),
  tray_seed text not null,
  wall_seed text not null,
  reveal_secret text not null,
  rules_version text not null default 'crunch-v1',
  reveal_horizon integer not null default 2 check (reveal_horizon >= 1 and reveal_horizon <= 8),
  tray_cursor integer not null default 0 check (tray_cursor >= 0),
  client_version text,
  device_token text,
  moves jsonb not null default '[]'::jsonb,
  verified_score integer,
  verified_survival_ms bigint,
  verified_poxels_popped integer,
  verified_move_count integer,
  verified_wall_depth integer,
  verified_lines_cleared integer,
  verified_best_lines_cleared integer,
  verified_wall_cells_cleared integer,
  verified_time_bonus_ms integer,
  verified_critical_escapes integer,
  rejection_reason text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists crunch_runs_user_id_started_at_idx
  on public.crunch_runs (user_id, started_at desc);

create index if not exists crunch_runs_status_started_at_idx
  on public.crunch_runs (status, started_at desc);

alter table public.crunch_runs enable row level security;
revoke all on table public.crunch_runs from anon, authenticated;

create table if not exists public.crunch_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  run_id uuid unique references public.crunch_runs(id) on delete set null,
  score integer not null check (score >= 0),
  survival_ms bigint not null default 0 check (survival_ms >= 0),
  poxels_popped integer not null default 0 check (poxels_popped >= 0),
  move_count integer,
  wall_depth integer,
  lines_cleared integer,
  best_lines_cleared integer,
  wall_cells_cleared integer,
  time_bonus_ms integer,
  critical_escapes integer,
  created_at timestamptz not null default now()
);

create index if not exists crunch_scores_score_created_at_idx
  on public.crunch_scores (score desc, created_at asc);

create index if not exists crunch_scores_user_id_created_at_idx
  on public.crunch_scores (user_id, created_at desc);

alter table public.crunch_scores enable row level security;
revoke all on table public.crunch_scores from anon, authenticated;
grant select on table public.crunch_scores to anon, authenticated;

drop policy if exists "crunch scores are readable by everyone" on public.crunch_scores;
create policy "crunch scores are readable by everyone"
on public.crunch_scores
for select
to authenticated, anon
using (true);

drop policy if exists "users can read their own crunch runs" on public.crunch_runs;

-- Notes:
-- 1. `tray_seed` and `wall_seed` remain server-side only. Browser clients should never
--    receive enough information to derive the full run sequence.
-- 2. `reveal_horizon` tracks how many trays ahead the server is willing to reveal/buffer.
-- 3. Client writes should continue to go through Edge Functions only after full replay and
--    timing verification have been implemented.
