create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index if not exists scores_score_created_at_idx
  on public.scores (score desc, created_at asc);

create index if not exists scores_user_id_created_at_idx
  on public.scores (user_id, created_at desc);

alter table public.scores enable row level security;
revoke all on table public.scores from anon, authenticated;
grant select on table public.scores to anon, authenticated;

drop policy if exists "scores are readable by everyone" on public.scores;
create policy "scores are readable by everyone"
on public.scores
for select
to authenticated, anon
using (true);

drop policy if exists "users can insert their own scores" on public.scores;

-- Intentionally leave the browser with no access here.
-- Public/global score reads are allowed so the seeded board can be shown.
-- Client-side score writes should only come back once a trusted server-side
-- verification path exists (for example via a Supabase Edge Function using the
-- service role key).
